export const careersData = [
  {
    id: 1,
    title: "Marketing Executive",
    job_name: "marketing_executive",
    category: "Marketing",
    location: "Remote / On-site",
    type: "Full-time",
    salary: "$60,000 - $80,000",
    description:
      "Lead our marketing initiatives and drive brand awareness across multiple channels. As a Marketing Executive, you'll be at the forefront of our brand's growth, developing and executing strategies that resonate with our target audience.",
    responsibilities: [
      "Develop and execute comprehensive marketing strategies aligned with business objectives",
      "Manage social media campaigns and content creation across all platforms",
      "Analyze market trends and competitor activities to identify opportunities",
      "Collaborate with sales team to generate qualified leads and improve conversion rates",
      "Monitor and report on marketing performance metrics and ROI",
      "Plan and coordinate marketing events, webinars, and promotional campaigns",
      "Manage marketing budget and optimize spending for maximum impact",
      "Build and maintain relationships with media partners and influencers",
    ],
    requirements: [
      "3+ years of marketing experience in a similar role",
      "Strong understanding of digital marketing channels and best practices",
      "Excellent communication and presentation skills",
      "Data-driven mindset with experience in analytics tools",
      "Bachelor's degree in Marketing, Business, or related field",
      "Proven track record of successful marketing campaigns",
      "Experience with CRM and marketing automation tools",
      "Creative thinking and problem-solving abilities",
    ],
    niceToHave: [
      "Experience with SEO/SEM strategies",
      "Knowledge of graphic design tools",
      "Project management certification",
      "Experience in B2B marketing",
    ],
    benefits: [
      "Competitive salary and performance bonuses",
      "Health, dental, and vision insurance",
      "Flexible work hours and remote work options",
      "Professional development budget",
      "401(k) matching",
      "Unlimited PTO policy",
      "Modern office with free snacks and drinks",
      "Regular team building events",
    ],
  },
  {
    id: 2,
    title: "Graphic Artist",
    job_name: "graphic_artist",
    category: "Design",
    location: "Remote",
    type: "Full-time",
    salary: "$50,000 - $70,000",
    description:
      "Create stunning visual content that brings our brand to life. Join our creative team and help shape our visual identity across all platforms.",
    responsibilities: [
      "Design graphics for web, social media, and print materials",
      "Develop brand assets and maintain visual consistency",
      "Create illustrations, infographics, and promotional materials",
      "Collaborate with marketing team on campaign visuals",
      "Stay updated with design trends and best practices",
      "Prepare files for production and coordinate with vendors",
      "Manage multiple projects with tight deadlines",
    ],
    requirements: [
      "Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
      "Strong portfolio demonstrating creative skills",
      "2+ years of graphic design experience",
      "Attention to detail and color theory knowledge",
      "Understanding of design principles and typography",
      "Ability to work independently and collaboratively",
    ],
    niceToHave: [
      "Motion graphics experience (After Effects)",
      "3D design skills (Cinema 4D, Blender)",
      "Photography and photo editing skills",
      "UI/UX design knowledge",
    ],
    benefits: [
      "Competitive salary",
      "Health and dental insurance",
      "100% remote work",
      "Creative freedom and autonomy",
      "Professional development budget",
      "Latest design software and tools",
      "Flexible hours",
    ],
  },
  {
    id: 3,
    title: "Next.js Developer",
    job_name: "nextjs_developer",
    category: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$80,000 - $120,000",
    description:
      "Build and optimize modern web applications using Next.js and React. Work on cutting-edge projects and contribute to our technical excellence.",
    responsibilities: [
      "Develop responsive web applications using Next.js and React",
      "Implement server-side rendering and static site generation",
      "Write clean, maintainable, and well-documented code",
      "Optimize application performance and SEO",
      "Collaborate with designers and backend developers",
      "Participate in code reviews and technical discussions",
      "Debug and resolve technical issues",
      "Stay current with latest web technologies",
    ],
    requirements: [
      "3+ years of React and Next.js experience",
      "Strong knowledge of JavaScript/TypeScript",
      "Experience with RESTful APIs and state management",
      "Understanding of web performance optimization",
      "Proficiency with Git and version control",
      "Experience with testing frameworks (Jest, React Testing Library)",
      "Strong problem-solving skills",
    ],
    niceToHave: [
      "Experience with GraphQL and Apollo",
      "DevOps knowledge (Docker, CI/CD)",
      "Open source contributions",
      "Experience with design systems",
      "Backend development experience",
    ],
    benefits: [
      "Competitive salary and equity",
      "Stock options",
      "Latest MacBook Pro or preferred equipment",
      "Conference attendance and learning budget",
      "Remote work from anywhere",
      "Health, dental, and vision insurance",
      "Unlimited PTO",
      "Home office setup budget",
    ],
  },
  {
    id: 4,
    title: "Content Writer",
    job_name: "content_writer",
    category: "Marketing",
    location: "Remote",
    type: "Full-time / Part-time",
    salary: "$45,000 - $65,000",
    description:
      "Craft compelling content that engages our audience and drives results. Your words will shape our brand voice and connect with our community.",
    responsibilities: [
      "Write blog posts, articles, and website copy",
      "Create engaging social media content",
      "Develop email marketing campaigns",
      "Research industry trends and topics",
      "Edit and proofread content for accuracy",
      "Optimize content for SEO",
      "Collaborate with marketing and design teams",
      "Maintain brand voice and style guidelines",
    ],
    requirements: [
      "Excellent writing and editing skills",
      "2+ years of content writing experience",
      "SEO knowledge and best practices",
      "Ability to adapt tone for different audiences",
      "Strong research skills",
      "Portfolio of published work",
      "Deadline-driven and organized",
    ],
    niceToHave: [
      "Experience with content management systems",
      "Basic HTML/CSS knowledge",
      "Social media marketing experience",
      "Video script writing",
      "Technical writing skills",
    ],
    benefits: [
      "Competitive salary",
      "Flexible schedule (part-time available)",
      "Remote work",
      "Professional development",
      "Creative freedom",
      "Health insurance (full-time)",
      "Paid writing courses",
    ],
  },
  {
    id: 5,
    title: "UI/UX Designer",
    job_name: "ui_ux_designer",
    category: "Design",
    location: "Hybrid",
    type: "Full-time",
    salary: "$70,000 - $95,000",
    description:
      "Design intuitive and beautiful user experiences for our digital products. Create interfaces that users love and help drive business success.",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Design responsive interfaces for web and mobile",
      "Collaborate with developers to ensure design implementation",
      "Maintain and evolve design system",
      "Present design concepts to stakeholders",
      "Analyze user feedback and iterate designs",
      "Create user flows and journey maps",
    ],
    requirements: [
      "3+ years of UI/UX design experience",
      "Proficiency in Figma or similar design tools",
      "Strong portfolio showcasing design process",
      "Understanding of accessibility standards (WCAG)",
      "Knowledge of design systems and component libraries",
      "Excellent communication skills",
      "User-centered design approach",
    ],
    niceToHave: [
      "Experience with prototyping tools (Principle, ProtoPie)",
      "Basic front-end development skills",
      "Animation and micro-interaction design",
      "Experience with design tokens",
      "UX writing skills",
    ],
    benefits: [
      "Competitive salary",
      "Hybrid work model",
      "Latest design tools and software",
      "Professional development budget",
      "Health and wellness benefits",
      "401(k) matching",
      "Ergonomic office setup",
      "Design conference attendance",
    ],
  },
  {
    id: 6,
    title: "Backend Developer",
    job_name: "backend_developer",
    category: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$85,000 - $130,000",
    description:
      "Build scalable backend systems and APIs that power our applications. Work on high-performance systems that serve millions of users.",
    responsibilities: [
      "Design and implement RESTful APIs",
      "Optimize database queries and performance",
      "Implement authentication and security measures",
      "Write unit and integration tests",
      "Deploy and monitor applications",
      "Maintain and improve existing codebase",
      "Collaborate with frontend developers",
      "Participate in architecture decisions",
    ],
    requirements: [
      "3+ years of backend development experience",
      "Proficiency in Node.js, Python, or similar",
      "Experience with databases (MongoDB, PostgreSQL)",
      "Knowledge of cloud platforms (AWS, GCP, Azure)",
      "Understanding of API design principles",
      "Experience with containerization (Docker)",
      "Strong debugging and optimization skills",
    ],
    niceToHave: [
      "Microservices architecture experience",
      "Message queue systems (RabbitMQ, Kafka)",
      "GraphQL implementation",
      "DevOps and CI/CD pipelines",
      "Security best practices and OWASP",
    ],
    benefits: [
      "Competitive salary and equity",
      "Remote-first culture",
      "Top-tier equipment",
      "Learning and development budget",
      "Health, dental, and vision insurance",
      "Unlimited PTO",
      "Annual team retreats",
      "Stock options",
    ],
  },
  {
    id: 7,
    title: "Social Media Manager",
    job_name: "social_media_manager",
    category: "Marketing",
    location: "Remote",
    type: "Full-time",
    salary: "$55,000 - $75,000",
    description:
      "Manage our social media presence and build engaged communities. Create content that resonates and grow our brand across all platforms.",
    responsibilities: [
      "Develop social media strategy across platforms",
      "Create and schedule engaging content",
      "Monitor and respond to community engagement",
      "Analyze social media metrics and insights",
      "Stay updated with social media trends",
      "Manage social media advertising campaigns",
      "Collaborate with content creators and designers",
      "Build relationships with influencers",
    ],
    requirements: [
      "2+ years of social media management experience",
      "Strong understanding of major social platforms",
      "Creative content creation skills",
      "Experience with social media analytics tools",
      "Excellent written communication",
      "Knowledge of social media advertising",
      "Community management experience",
    ],
    niceToHave: [
      "Experience with social media management tools (Hootsuite, Buffer)",
      "Basic graphic design skills",
      "Video editing experience",
      "Influencer marketing experience",
      "Crisis management skills",
    ],
    benefits: [
      "Competitive salary",
      "Remote work flexibility",
      "Creative autonomy",
      "Professional development",
      "Health insurance",
      "PTO and flexible hours",
      "Social media tools and courses",
      "Team events",
    ],
  },
  {
    id: 8,
    title: "Product Manager",
    job_name: "product_manager",
    category: "Product",
    location: "Hybrid",
    type: "Full-time",
    salary: "$90,000 - $140,000",
    description:
      "Drive product vision and strategy to deliver exceptional user experiences. Lead cross-functional teams and shape the future of our products.",
    responsibilities: [
      "Define product roadmap and priorities",
      "Gather and analyze user feedback",
      "Work with cross-functional teams",
      "Create product requirements and specifications",
      "Monitor product performance and iterate",
      "Conduct market research and competitive analysis",
      "Lead product launches and go-to-market strategy",
      "Communicate product vision to stakeholders",
    ],
    requirements: [
      "4+ years of product management experience",
      "Strong analytical and problem-solving skills",
      "Experience with agile methodologies",
      "Excellent communication and leadership abilities",
      "Data-driven decision making",
      "Understanding of user-centered design",
      "Technical background or strong technical aptitude",
    ],
    niceToHave: [
      "MBA or relevant advanced degree",
      "Experience in SaaS products",
      "SQL and data analysis skills",
      "Experience with product analytics tools",
      "Background in engineering or design",
    ],
    benefits: [
      "Competitive salary and equity",
      "Hybrid work environment",
      "Leadership development programs",
      "Health, dental, and vision insurance",
      "401(k) with company match",
      "Generous PTO",
      "Conference and training budget",
      "Stock options",
    ],
  },
];

// Helper function to get job by ID
export const getJobById = (id) => {
  return careersData.find((job) => job.id === parseInt(id));
};

// Helper function to get job by job_name
export const getJobByName = (jobName) => {
  return careersData.find((job) => job.job_name === jobName);
};

// Helper function to get all categories
export const getCategories = () => {
  return ["all", ...new Set(careersData.map((job) => job.category))];
};

// Helper function to filter jobs by category
export const getJobsByCategory = (category) => {
  if (category === "all") return careersData;
  return careersData.filter((job) => job.category === category);
};

// Helper function to get all jobs
export const getAllJobs = () => {
  return careersData;
};
